"""
command_table.py
The full alias -> command-name table transcribed from Autodesk's AutoCAD
Shortcuts Guide (one-key shortcuts + full A-Z hotkey list). Every alias
here is recognized at the command line. IMPLEMENTED tracks which ones have
a real handler wired up in commands.py right now; anything else prints an
honest "not implemented yet" message instead of pretending to work.
"""

# alias -> (full command name, description)
COMMAND_ALIASES = {
    # One-key shortcuts
    "Q": ("QSAVE", "Saves the current drawing."),
    "A": ("ARC", "Creates an arc."),
    "Z": ("ZOOM", "Increases or decreases magnification."),
    "W": ("WBLOCK", "Writes objects to a new drawing file."),
    "S": ("STRETCH", "Stretches objects crossed by a selection window."),
    "X": ("EXPLODE", "Breaks a compound object into components."),
    "E": ("ERASE", "Removes objects from a drawing."),
    "D": ("DIMSTYLE", "Creates and modifies dimension styles."),
    "C": ("CIRCLE", "Creates a circle."),
    "R": ("REDRAW", "Refreshes the display."),
    "F": ("FILLET", "Rounds and fillets edges."),
    "V": ("VIEW", "Saves/restores named views."),
    "T": ("MTEXT", "Creates a multiline text object."),
    "G": ("GROUP", "Creates/manages groups."),
    "B": ("BLOCK", "Creates a block definition."),
    "H": ("HATCH", "Fills an area with a hatch/gradient."),
    "J": ("JOIN", "Joins objects into one."),
    "M": ("MOVE", "Moves objects."),
    "I": ("INSERT", "Inserts a block/drawing."),
    "O": ("OFFSET", "Creates parallel/concentric geometry."),
    "L": ("LINE", "Creates straight line segments."),
    "P": ("PAN", "Pans the view / adds param to dynamic block."),

    # A
    "AA": ("AREA", "Calculates area/perimeter."),
    "ADC": ("ADCENTER", "Manages/inserts blocks, xrefs, hatch patterns."),
    "AL": ("ALIGN", "Aligns objects with other objects."),
    "AP": ("APPLOAD", "Loads an application."),
    "AR": ("ARRAY", "Creates multiple copies in a pattern."),
    "ARR": ("ACTRECORD", "Starts the Action Recorder."),
    "ARM": ("ACTUSERMESSAGE", "Inserts a user message into an action macro."),
    "ARU": ("ACTUSERINPUT", "Pauses for user input in an action macro."),
    "ARS": ("ACTSTOP", "Stops the Action Recorder."),
    "ATI": ("ATTIPEDIT", "Changes textual content of a block attribute."),
    "ATT": ("ATTDEF", "Redefines a block and updates attributes."),
    "ATE": ("ATTEDIT", "Changes attribute information in a block."),
    # B
    "BC": ("BCLOSE", "Closes the Block Editor."),
    "BE": ("BEDIT", "Opens block definition in Block Editor."),
    "BH": ("HATCH", "Fills an area with a hatch/gradient."),
    "BO": ("BOUNDARY", "Creates a region/polyline from an enclosed area."),
    "BR": ("BREAK", "Breaks the selected object between two points."),
    "BS": ("BSAVE", "Saves the current block definition."),
    "BVS": ("BVSTATE", "Creates/sets/deletes a visibility state."),
    # C
    "CAM": ("CAMERA", "Sets a camera/target for 3D perspective."),
    "CBAR": ("CONSTRAINTBAR", "Shows available geometric constraints."),
    "CH": ("PROPERTIES", "Controls properties of existing objects."),
    "CHA": ("CHAMFER", "Bevels the edges of objects."),
    "CHK": ("CHECKSTANDARDS", "Checks drawing for standards violations."),
    "CLI": ("COMMANDLINE", "Displays the Command Line window."),
    "COL": ("COLOR", "Sets the color for new objects."),
    "CO": ("COPY", "Copies objects."),
    "CT": ("CTABLESTYLE", "Sets current table style."),
    "CUBE": ("NAVVCUBE", "Controls ViewCube visibility."),
    "CYL": ("CYLINDER", "Creates a 3D solid cylinder."),
    # D
    "DAN": ("DIMANG", "Creates an angular dimension."),
    "DAL": ("DIMLINEAR", "Creates an aligned/linear dimension."),
    "DLI": ("DIMLINEAR", "Creates a linear dimension."),
    "DAR": ("DIMARC", "Creates an arc length dimension."),
    "DBA": ("DIMBASELINE", "Creates a baseline dimension."),
    "DBC": ("DBCONNECT", "Interface to external database tables."),
    "DCE": ("DIMCENTER", "Creates center mark/centerlines."),
    "DCO": ("DIMCONTINUE", "Creates a continued dimension."),
    "DCON": ("DIMCONSTRAINT", "Applies dimensional constraints."),
    "DDA": ("DIMDISASSOCIATE", "Removes associativity from dimensions."),
    "DDI": ("DIMDIA", "Creates a diameter dimension."),
    "DED": ("DIMEDIT", "Edits dimension text/extension lines."),
    "DI": ("DIST", "Measures distance and angle between two points."),
    "DIV": ("DIVIDE", "Creates evenly spaced points/blocks."),
    "DJL": ("DIMJOGLINE", "Adds/removes a jog line on a dimension."),
    "DJO": ("DIMJOGGED", "Creates jogged dimensions."),
    "DL": ("DATALINK", "Opens the Data Link dialog."),
    "DLU": ("DATALINKUPDATE", "Updates data to/from external data link."),
    "DO": ("DONUT", "Creates a filled circle or wide ring."),
    "DOR": ("DIMORDINATE", "Creates ordinate dimensions."),
    "DOV": ("DIMOVERRIDE", "Controls dimension system-variable overrides."),
    "DR": ("DRAWORDER", "Changes draw order of objects."),
    "DRA": ("DIMRAD", "Creates a radius dimension."),
    "DRE": ("DIMREASSOCIATE", "Re-associates dimensions to objects."),
    "DRM": ("DRAWINGRECOVERY", "Lists recoverable drawing files."),
    "DS": ("DSETTINGS", "Sets grid, snap, osnap, dynamic input."),
    "DT": ("TEXT", "Creates a single-line text object."),
    "DV": ("DVIEW", "Defines parallel/perspective views."),
    "DX": ("DATAEXTRACTION", "Extracts drawing data to a table/file."),
    # E-F
    "ED": ("DDEDIT", "Edits single-line text/dimension text."),
    "EL": ("ELLIPSE", "Creates an ellipse or elliptical arc."),
    "EPDF": ("EXPORTPDF", "Exports drawing to PDF."),
    "ER": ("EXTERNALREFERENCES", "Opens the External References palette."),
    "EX": ("EXTEND", "Extends objects to meet other objects."),
    "EXIT": ("QUIT", "Exits the program."),
    "EXP": ("EXPORT", "Saves objects to a different file format."),
    "EXT": ("EXTRUDE", "Extends a 2D object/face into 3D space."),
    "FI": ("FILTER", "Creates a selection-set filter."),
    "FS": ("FSMODE", "Selection set of objects touching selected object."),
    "FSHOT": ("FLATSHOT", "2D representation of 3D objects from current view."),
    # G-H
    "GCON": ("GEOCONSTRAINT", "Applies/persists geometric relationships."),
    "GD": ("GRADIENT", "Fills an area with a gradient."),
    "GEO": ("GEOGRAPHICLOCATION", "Sets geographic location info."),
    "HE": ("HATCHEDIT", "Modifies an existing hatch/fill."),
    "HI": ("HIDE", "Regenerates 3D wireframe with hidden lines suppressed."),
    # I-K
    "IAD": ("IMAGEADJUST", "Controls brightness/contrast/fade of images."),
    "IAT": ("IMAGEATTACH", "Inserts a reference to an image file."),
    "ICL": ("IMAGECLIP", "Crops the display of a selected image."),
    "ID": ("ID", "Displays UCS coordinate values of a point."),
    "IM": ("IMAGE", "Displays the External References palette."),
    "IMP": ("IMPORT", "Imports files of different formats."),
    "IN": ("INTERSECT", "Creates solid/surface/region from overlaps."),
    "INF": ("INTERFERE", "Creates temp solid from interference of two sets."),
    "IO": ("INSERTOBJ", "Inserts a linked or embedded object."),
    "JOG": ("DIMJOGGED", "Creates jogged dimensions."),
    # L-M
    "LA": ("LAYER", "Manages layers and layer properties."),
    "LAS": ("LAYERSTATE", "Saves/restores/manages named layer states."),
    "LE": ("LEADER", "Creates a leader and leader annotation."),
    "LEN": ("LENGTHEN", "Changes the length of objects/included angle."),
    "LESS": ("MESHSMOOTHLESS", "Decreases mesh smoothness by one level."),
    "LI": ("LIST", "Displays property data for selected objects."),
    "LO": ("LAYOUT", "Creates and modifies drawing layout tabs."),
    "LT": ("LINETYPE", "Loads, sets, and modifies linetypes."),
    "LTS": ("LTSCALE", "Changes linetype scale factor."),
    "LW": ("LWEIGHT", "Sets current lineweight/display options."),
    "MA": ("MATCHPROP", "Applies properties of one object to others."),
    "MAT": ("MATERIALS", "Shows/hides the Materials window."),
    "ME": ("MEASURE", "Creates points/blocks at measured intervals."),
    "MEA": ("MEASUREGEOM", "Measures distance, radius, angle, area, volume."),
    "MI": ("MIRROR", "Creates a mirrored copy of selected objects."),
    "ML": ("MLINE", "Creates multiple parallel lines."),
    "MLA": ("MLEADERALIGN", "Aligns and spaces selected multileaders."),
    "MLC": ("MLEADERCOLLECT", "Organizes multileaders into rows/columns."),
    "MLD": ("MLEADER", "Creates a multileader object."),
    "MLE": ("MLEADEREDIT", "Adds/removes leader lines to a multileader."),
    "MLS": ("MLEADERSTYLE", "Creates and modifies multileader styles."),
    "MO": ("PROPERTIES", "Controls properties of existing objects."),
    "MORE": ("MESHSMOOTHMORE", "Increases mesh smoothness by one level."),
    "MS": ("MSPACE", "Switches from paper space to model space."),
    "MSM": ("MARKUP", "Opens the Markup Set Manager."),
    "MV": ("MVIEW", "Creates and controls layout viewports."),
    # N-O
    "NORTH": ("GEOGRAPHICLOCATION", "Specifies geographic location info."),
    "NSHOT": ("NEWSHOT", "Creates a named view with motion."),
    "NVIEW": ("NEWVIEW", "Creates a named view with no motion."),
    "OP": ("OPTIONS", "Customizes the program settings."),
    "ORBIT": ("3DORBIT", "Rotates the view in constrained 3D orbit."),
    "OS": ("OSNAP", "Sets running object snap modes."),
    # P
    "PA": ("PASTESPEC", "Pastes clipboard objects, controls data format."),
    "PAR": ("PARAMETERS", "Controls associative parameters in drawing."),
    "PARAM": ("BPARAMETER", "Adds a parameter to a dynamic block."),
    "PATCH": ("SURFPATCH", "Creates a new surface capping an edge loop."),
    "PC": ("POINTCLOUD", "Options to create/attach point cloud files."),
    "PCATTACH": ("POINTCLOUDATTACH", "Inserts an indexed point cloud file."),
    "PCINDEX": ("POINTCLOUDINDEX", "Creates an indexed point cloud file."),
    "PE": ("PEDIT", "Edits polylines and 3D polygon meshes."),
    "PL": ("PLINE", "Creates a 2D polyline."),
    "PO": ("POINT", "Creates a point object."),
    "POFF": ("HIDEPALETTES", "Hides currently displayed palettes."),
    "POL": ("POLYGON", "Creates an equilateral closed polyline."),
    "PON": ("SHOWPALETTES", "Restores display of hidden palettes."),
    "PR": ("PROPERTIES", "Displays the Properties palette."),
    "PRE": ("PREVIEW", "Displays the drawing as it will be plotted."),
    "PRINT": ("PLOT", "Plots a drawing to a plotter/printer/file."),
    "PS": ("PSPACE", "Switches from model space to paper space."),
    "PSOLID": ("POLYSOLID", "Creates a 3D wall-like polysolid."),
    "PTW": ("PUBLISHTOWEB", "Creates HTML pages of selected drawings."),
    "PU": ("PURGE", "Removes unused items from the drawing."),
    "PYR": ("PYRAMID", "Creates a 3D solid pyramid."),
    # Q
    "QC": ("QUICKCALC", "Opens the QuickCalc calculator."),
    "QCUI": ("QUICKCUI", "Displays Customize User Interface Editor."),
    "QP": ("QUICKPROPERTIES", "Displays open drawings/layouts as previews."),
    "QSAVE": ("QSAVE", "Saves the current drawing."),
    "QVD": ("QVDRAWING", "Displays open drawings/layouts as previews."),
    "QVDC": ("QVDRAWINGCLOSE", "Closes preview images of open drawings."),
    "QVL": ("QVLAYOUT", "Displays preview images of model/layouts."),
    "QVLC": ("QVLAYOUTCLOSE", "Closes preview images of model/layouts."),
    # R
    "RA": ("REDRAWALL", "Refreshes the display in all viewports."),
    "RC": ("RENDERCROP", "Renders a specified rectangular crop area."),
    "RE": ("REGEN", "Regenerates the entire drawing."),
    "REA": ("REGENALL", "Regenerates drawing and refreshes all viewports."),
    "REC": ("RECTANG", "Creates a rectangular polyline."),
    "REG": ("REGION", "Converts an enclosed object into a region."),
    "REN": ("RENAME", "Changes names assigned to layers/dim styles."),
    "REV": ("REVOLVE", "Creates a 3D solid/surface by sweeping around axis."),
    "RO": ("ROTATE", "Rotates objects around a base point."),
    "RP": ("RENDERPRESETS", "Specifies reusable render presets."),
    "RPR": ("RPREF", "Advanced Render Settings palette."),
    "RR": ("RENDER", "Creates a photorealistic/shaded image."),
    "RW": ("RENDERWIN", "Displays the Render window."),
    # S
    "SC": ("SCALE", "Enlarges or reduces selected objects."),
    "SCR": ("SCRIPT", "Executes a sequence of commands from a script."),
    "SEC": ("SECTION", "Region from intersection of a plane and solids."),
    "SET": ("SETVAR", "Lists or changes system variable values."),
    "SHA": ("SHADEMODE", "Starts the VSCURRENT command."),
    "SL": ("SLICE", "Creates new solids/surfaces by slicing existing ones."),
    "SN": ("SNAP", "Restricts cursor movement to specified intervals."),
    "SO": ("SOLID", "Creates solid-filled triangles and quadrilaterals."),
    "SP": ("SPELL", "Checks spelling in a drawing."),
    "SPE": ("SPLINEDIT", "Edits a spline or spline-fit polyline."),
    "SPL": ("SPLINE", "Creates a smooth curve through/near points."),
    "SPLANE": ("SECTIONPLANE", "Creates a section object/cutting plane."),
    "SPLAY": ("SEQUENCEPLAY", "Plays named views in one category."),
    "SPLIT": ("MESHSPLIT", "Splits a mesh face into two faces."),
    "SSM": ("SHEETSET", "Opens the Sheet Set Manager."),
    "ST": ("STYLE", "Creates, modifies, or specifies text styles."),
    "STA": ("STANDARDS", "Manages association of standards files."),
    "SU": ("SUBTRACT", "Combines 3D solids/regions by subtraction."),
    # T
    "TA": ("TABLET", "Calibrates/configures a digitizing tablet."),
    "TB": ("TABLE", "Creates an empty table object."),
    "TEDIT": ("TEXTEDIT", "Edits a dimensional constraint/text object."),
    "TH": ("THICKNESS", "Sets default 3D thickness property."),
    "TI": ("TILEMODE", "Controls whether paper space can be accessed."),
    "TO": ("TOOLBAR", "Displays, hides, and customizes toolbars."),
    "TOL": ("TOLERANCE", "Creates geometric tolerances."),
    "TOR": ("TORUS", "Creates a donut-shaped 3D solid."),
    "TP": ("TOOLPALETTES", "Opens the Tool Palettes window."),
    "TR": ("TRIM", "Trims objects to meet edges of other objects."),
    "TS": ("TABLESTYLE", "Creates, modifies, or specifies table styles."),
    # U-W
    "UC": ("UCSMAN", "Manages defined user coordinate systems."),
    "UN": ("UNITS", "Controls coordinate and angle display formats."),
    "UNHIDE": ("UNISOLATEOBJECTS", "Displays objects hidden by isolate/hide."),
    "UNISOLATE": ("UNISOLATEOBJECTS", "Displays objects hidden by isolate/hide."),
    "UNI": ("UNION", "Unions two solids or two region objects."),
    "VGO": ("VIEWGO", "Restores a named view."),
    "VP": ("DDVPOINT", "Sets the 3D viewing direction."),
    "VPLAY": ("VIEWPLAY", "Plays the animation for a named view."),
    "VS": ("VSCURRENT", "Sets the visual style in current viewport."),
    "VSM": ("VISUALSTYLES", "Creates/modifies/applies visual styles."),
    "WE": ("WEDGE", "Creates a 3D solid wedge."),
    "WHEEL": ("NAVSWHEEL", "Displays a navigation wheel."),
    # X-Z
    "XA": ("XATTACH", "Inserts a DWG file as an external reference."),
    "XB": ("XBIND", "Binds named object definitions from an xref."),
    "XC": ("XCLIP", "Crops display of a selected xref/block reference."),
    "XL": ("XLINE", "Creates a line of infinite length."),
    "XR": ("XREF", "Starts the EXTERNALREFERENCES command."),
    "ZEBRA": ("ANALYSISZEBRA", "Projects stripes to analyze surface continuity."),
    "ZIP": ("ETRANSMIT", "Creates a self-extracting/zipped transmittal."),

    # ---- app-specific extras ----
    "GCODE": ("GCODEGEN", "Generate G-code from selected profile geometry."),
    "GCODEGEN": ("GCODEGEN", "Generate G-code from selected profile geometry."),
    "DIMLINEAR": ("DIMLINEAR", "Creates a linear dimension."),
    "DIMRAD": ("DIMRAD", "Creates a radius dimension."),
    "DIMDIA": ("DIMDIA", "Creates a diameter dimension."),
    "DIMANG": ("DIMANG", "Creates an angular dimension."),
    "LEADER": ("LEADER", "Creates a leader with text."),
    "OSNAP": ("OSNAP", "Sets running object snap modes."),
    "OPEN": ("OPEN", "Open a DXF/DWG drawing."),
    "SAVEAS": ("SAVEAS", "Save the drawing under a new name/format."),
    "NEW": ("NEW", "Start a new drawing."),
    "U": ("UNDO", "Undo the last action."),
    "REDO": ("REDO", "Redo the last undone action."),
    "SELECT": ("SELECT", "Select entities by window."),
    "ALL": ("SELECTALL", "Select all objects."),
}

# Full names also resolve to themselves (typing "LINE" works same as "L")
for _alias, (_full, _desc) in list(COMMAND_ALIASES.items()):
    COMMAND_ALIASES.setdefault(_full, (_full, _desc))


def resolve(text):
    """Return (command_name, description) or (None, None) if unknown."""
    key = text.strip().upper()
    return COMMAND_ALIASES.get(key, (None, None))
